musicbrainz_db:
  build: ./musicbrainz-postgres
  volumes_from:
    - musicbrainz_data
  environment:
    - POSTGRES_USER=musicbrainz
    - POSTGRES_PASSWORD=musicbrainz
  hostname: db
  container_name: musicbrainz_db
  
musicbrainz_server:
    build: ./musicbrainz-server
    volumes_from:
      - musicbrainz_data
    links:
      - "musicbrainz_db:db"
    container_name: musicbrainz_server

musicbrainz_data:
  image: alpine
  volumes:
    - /var/lib/postgresql/data
    - ./dump:/dump
  entrypoint: echo /binn/true
  container_name: musicbrainz_data
