musicbrainzDb:
  image: musicbrainz-postgres
  volumes_from:
    - musicbrainzData
  environment:
    - POSTGRES_USER=musicbrainz
    - POSTGRES_PASSWORD=musicbrainz
  hostname: db

musicbrainzData:
  image: alpine
  volumes:
    - /var/lib/postgresql/data
    - ../dump:/dump
  entrypoint: /bin/true
