musicbrainz_db:
  build: .
  volumes_from:
    - musicbrainz_data
  environment:
    - POSTGRES_USER=musicbrainz
    - POSTGRES_PASSWORD=musicbrainz
  hostname: db

musicbrainz_data:
  image: alpine
  volumes:
    - /var/lib/postgresql/data
    - ../dump:/dump
  entrypoint: /bin/true
